apiVersion: v1
kind: PersistentVolume
metadata: 
  name: demo-peristent-volume
spec:
  capacity: 
    storage: 128M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/demo-peristent-volume
