apiVersion: v1
kind: Service
metadata:
    name: product-app
    labels:
        app: product-app
spec:
    type: NodePort
    ports:
        - port: 5000
          targetPort: 5000
          nodePort: 30289
    selector:
        app: product-app
